<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use DB;

class ReportOracle extends Model
{
	
	protected $env;
	protected $db_mobile_ins;
	
	public function __construct() {
		$this->env = 'dev';
		$this->db_mobile_ins = ($this->env == 'production' ? DB::connection('mobile_ins') : DB::connection('mobile_ins_dev'));
	}
	
    public function EBCC_VALIDATION_ESTATE_HEAD()
	{
		$get = $this->db_mobile_ins->select("
				SELECT
					KUALITAS.NAMA_KUALITAS
				FROM
					TAP_DW.T_KUALITAS_PANEN@PRODDW_LINK KUALITAS
				WHERE
					KUALITAS.ACTIVE_STATUS = 'YES'
				ORDER BY 
					KUALITAS.GROUP_KUALITAS ASC,
					KUALITAS.UOM ASC,
					KUALITAS.NAMA_KUALITAS ASC
		");
		return $get;
	}
	
    public function EBCC_VALIDATION($REPORT_TYPE , $START_DATE , $END_DATE , $REGION_CODE , $COMP_CODE , $BA_CODE , $AFD_CODE , $BLOCK_CODE)
	{
		$where = "";
		
		if($REPORT_TYPE){
			if($REPORT_TYPE=='EBCC_VALIDATION_ESTATE'){
				$where .= " and SUBSTR( EBCC_HEADER.EBCC_VALIDATION_CODE, 0, 1 ) = 'V'";
			}else{
				$where .= " and SUBSTR( EBCC_HEADER.EBCC_VALIDATION_CODE, 0, 1 ) = 'V'";
			}
		}
		
		$where .= $START_DATE ? " and EBCC_HEADER.SYNC_TIME >= TO_TIMESTAMP('$START_DATE 00:00:00','DD-MM-YYYY HH24:MI:SS')  ": "";
		$where .= $END_DATE ? " and EBCC_HEADER.SYNC_TIME <= TO_TIMESTAMP('$END_DATE 23:59:59','DD-MM-YYYY HH24:MI:SS')  ": "";		
		$where .= $REGION_CODE ? " and EST.REGION_CODE = '$REGION_CODE'  ": "";
		$where .= $COMP_CODE ? " and EST.COMP_CODE = '$COMP_CODE'  ": "";
		$where .= $BA_CODE ? " and EBCC_HEADER.WERKS = '$BA_CODE'  ": "";
		$where .= $AFD_CODE ? " and EBCC_HEADER.WERKS||EBCC_HEADER.AFD_CODE = '$AFD_CODE'  ": "";
		$where .= $BLOCK_CODE ? " and EBCC_HEADER.WERKS||EBCC_HEADER.AFD_CODE||EBCC_HEADER.BLOCK_CODE = '$BLOCK_CODE'  ": "";
		
		$sql = "
				SELECT
					EBCC_HEADER.EBCC_VALIDATION_CODE,
					EST.WERKS,
					EST.EST_NAME,
					EBCC_HEADER.AFD_CODE,
					EBCC_HEADER.BLOCK_CODE,
					EBCC_HEADER.NO_TPH,
					EBCC_HEADER.STATUS_TPH_SCAN,
					EBCC_HEADER.ALASAN_MANUAL,
					EBCC_HEADER.LAT_TPH,
					EBCC_HEADER.LON_TPH,
					EBCC_HEADER.DELIVERY_CODE,
					EBCC_HEADER.STATUS_DELIVERY_CODE,
					USER_AUTH.EMPLOYEE_NIK AS NIK_VALIDATOR,
					HRIS.EMPLOYEE_FULLNAME AS NAMA_VALIDATOR,
					HRIS.EMPLOYEE_POSITION AS JABATAN_VALIDATOR,
					EBCC_DETAIL.*
				FROM
					MOBILE_INSPECTION.TR_EBCC_VALIDATION_H EBCC_HEADER
					LEFT JOIN MOBILE_INSPECTION.TM_USER_AUTH USER_AUTH ON 
						USER_AUTH.USER_AUTH_CODE = EBCC_HEADER.INSERT_USER
					LEFT JOIN TAP_DW.TM_EMPLOYEE_HRIS@PRODDW_LINK HRIS ON
						HRIS.EMPLOYEE_NIK = USER_AUTH.EMPLOYEE_NIK
					LEFT JOIN TAP_DW.TM_EST@PRODDW_LINK EST ON 
						EST.WERKS = EBCC_HEADER.WERKS 
						AND SYSDATE BETWEEN EST.START_VALID AND EST.END_VALID
					INNER JOIN (
						SELECT * FROM (
							SELECT
								KUALITAS.ID_KUALITAS,
								EBCC_DETAIL.EBCC_VALIDATION_CODE,
								EBCC_DETAIL.JUMLAH
							FROM
								TAP_DW.T_KUALITAS_PANEN@PRODDW_LINK KUALITAS
								LEFT JOIN MOBILE_INSPECTION.TR_EBCC_VALIDATION_D EBCC_DETAIL ON EBCC_DETAIL.ID_KUALITAS = KUALITAS.ID_KUALITAS
							WHERE
								KUALITAS.ACTIVE_STATUS = 'YES'
							ORDER BY 
								KUALITAS.GROUP_KUALITAS ASC,
								KUALITAS.UOM ASC,
								KUALITAS.NAMA_KUALITAS ASC
						)
						PIVOT (
							SUM( JUMLAH )
							FOR ID_KUALITAS IN ( 
								1 as ID_KUALITAS_1, 
								2 as ID_KUALITAS_2, 
								3 as ID_KUALITAS_3, 
								4 as ID_KUALITAS_4, 
								5 as ID_KUALITAS_5, 
								6 as ID_KUALITAS_6, 
								7 as ID_KUALITAS_7, 
								8 as ID_KUALITAS_8, 
								9 as ID_KUALITAS_9, 
								10 as ID_KUALITAS_10, 
								11 as ID_KUALITAS_11, 
								12 as ID_KUALITAS_12, 
								13 as ID_KUALITAS_13, 
								14 as ID_KUALITAS_14, 
								15 as ID_KUALITAS_15, 
								16 as ID_KUALITAS_16 
							)
						)
						WHERE EBCC_VALIDATION_CODE IS NOT NULL
					) EBCC_DETAIL ON
						EBCC_DETAIL.EBCC_VALIDATION_CODE = EBCC_HEADER.EBCC_VALIDATION_CODE
				WHERE 1=1
				$where
		";
		
		$get = $this->db_mobile_ins->select($sql);
		return $get;
	}
}
